#!/usr/bin/env python3
"""mkshelf — generate Copyist's own SFZ mappings for shelf libraries
that ship samples without maps.

Some of the best openly licensed recordings arrive as bare folders of
WAVs: VSCO2 CE's recorded trombone falls (its own SFZ never mapped
them), VCSL's tenor saxophone and saxello. This writes the .sfz maps
into <shelf>/Copyist-Extras/, deterministically, from what is actually
on disk — rerun it after installing libraries; edits to its output do
not last.

Two conventions handled the hard-won way:
- VCSL names octaves Yamaha-style, one below MIDI (their C4 sounds
  MIDI 72) — measured on the tenor's C4 by harmonic probe, 2026-09-21,
  not assumed. Every VCSL key gets +12.
- Round robins ride seq_length/seq_position from _varN / _N suffixes.
"""
import os
import re
import sys

NOTE = {'C': 0, 'C#': 1, 'Db': 1, 'D': 2, 'D#': 3, 'Eb': 3, 'E': 4,
        'F': 5, 'F#': 6, 'Gb': 6, 'G': 7, 'G#': 8, 'Ab': 8, 'A': 9,
        'A#': 10, 'Bb': 10, 'B': 11}
_NOTE_RE = re.compile(r'^([A-G][#b]?)(-?\d)$')


def scan(folder, octave_shift=0):
    """WAV folder -> {midi: [files]}, pitch read from the filename."""
    by_key = {}
    for f in sorted(os.listdir(folder)):
        if not f.lower().endswith('.wav'):
            continue
        midi = None
        for tok in os.path.splitext(f)[0].split('_'):
            m = _NOTE_RE.match(tok)
            if m:
                midi = (NOTE[m.group(1)]
                        + (int(m.group(2)) + 1) * 12
                        + octave_shift)
        if midi is not None and 0 <= midi <= 127:
            by_key.setdefault(midi, []).append(f)
    return by_key


def write_map(out_path, sample_dir_rel, by_key, spread=24):
    """One .sfz: key windows split between neighbors, round robins
    from the per-key file count."""
    keys = sorted(by_key)
    if not keys:
        return False
    lines = ['// Generated by Copyist mkshelf — edits do not last.',
             '<control>',
             'default_path=%s' % sample_dir_rel.replace(os.sep, '/'),
             '']
    for i, k in enumerate(keys):
        lo = (keys[i - 1] + k) // 2 + 1 if i else max(k - spread, 0)
        hi = (k + keys[i + 1]) // 2 if i + 1 < len(keys) \
            else min(k + spread, 127)
        rrs = by_key[k]
        for pos, f in enumerate(rrs, 1):
            rr = (' seq_length=%d seq_position=%d' % (len(rrs), pos)
                  if len(rrs) > 1 else '')
            lines.append('<region> sample=%s lokey=%d hikey=%d '
                         'pitch_keycenter=%d%s' % (f, lo, hi, k, rr))
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, 'w', encoding='utf-8') as fh:
        fh.write('\n'.join(lines) + '\n')
    return True


# (source folder under the shelf, octave shift, output name, spread)
MAPS = [
    ('VSCO2-CE/Brass/OldTrombone/Fall', 0, 'trombone-falls.sfz', 24),
    ('VCSL/Aerophones/Reed Aerophones/Tenor Saxophone/Vibrato', 12,
     'tenor-sax.sfz', 3),
    ('VCSL/Aerophones/Reed Aerophones/Tenor Saxophone/Staccato', 12,
     'tenor-sax-stac.sfz', 3),
    ('VCSL/Aerophones/Reed Aerophones/Saxello/Vibrato', 12,
     'saxello.sfz', 3),
    ('VCSL/Aerophones/Reed Aerophones/Saxello/Staccato', 12,
     'saxello-stac.sfz', 3),
]


def main(shelf):
    made = []
    for rel, shift, name, spread in MAPS:
        src = os.path.join(shelf, rel)
        if not os.path.isdir(src):
            continue
        out = os.path.join(shelf, 'Copyist-Extras', name)
        if write_map(out, os.path.join('..', rel), scan(src, shift),
                     spread):
            made.append(name)
    return made


if __name__ == '__main__':
    shelf = sys.argv[1] if len(sys.argv) > 1 else os.path.expanduser(
        '~/Library/Application Support/Copyist/Sounds')
    for name in main(shelf):
        print('wrote', name)
