#!/usr/bin/env python3
"""mkshelf — generate Copyist's own SFZ mappings for shelf libraries
that ship samples without maps.

Some of the best openly licensed recordings arrive as bare folders of
WAVs: VSCO2 CE's recorded trombone falls (its own SFZ never mapped
them), VCSL's tenor saxophone and saxello. This writes the .sfz maps
into <shelf>/Copyist-Extras/, deterministically, from what is actually
on disk — rerun it after installing libraries; edits to its output do
not last.

Two conventions handled the hard-won way:
- VCSL names octaves Yamaha-style, one below MIDI (their C4 sounds
  MIDI 72) — measured on the tenor's C4 by harmonic probe, 2026-09-21,
  not assumed. Every VCSL key gets +12.
- Round robins ride seq_length/seq_position from _varN / _N suffixes.
"""
import os
import re
import sys

NOTE = {'C': 0, 'C#': 1, 'Db': 1, 'D': 2, 'D#': 3, 'Eb': 3, 'E': 4,
        'F': 5, 'F#': 6, 'Gb': 6, 'G': 7, 'G#': 8, 'Ab': 8, 'A': 9,
        'A#': 10, 'Bb': 10, 'B': 11}
_NOTE_RE = re.compile(r'^([A-G][#b]?)(-?\d)$')


def scan(folder, octave_shift=0):
    """WAV folder -> {midi: [files]}, pitch read from the filename."""
    by_key = {}
    for f in sorted(os.listdir(folder)):
        if not f.lower().endswith('.wav'):
            continue
        midi = None
        for tok in os.path.splitext(f)[0].split('_'):
            m = _NOTE_RE.match(tok)
            if m:
                midi = (NOTE[m.group(1)]
                        + (int(m.group(2)) + 1) * 12
                        + octave_shift)
        if midi is not None and 0 <= midi <= 127:
            by_key.setdefault(midi, []).append(f)
    return by_key


def write_map(out_path, sample_dir_rel, by_key, spread=24):
    """One .sfz: key windows split between neighbors, round robins
    from the per-key file count."""
    keys = sorted(by_key)
    if not keys:
        return False
    lines = ['// Generated by Copyist mkshelf — edits do not last.',
             '<control>',
             'default_path=%s' % sample_dir_rel.replace(os.sep, '/'),
             '']
    for i, k in enumerate(keys):
        lo = (keys[i - 1] + k) // 2 + 1 if i else max(k - spread, 0)
        hi = (k + keys[i + 1]) // 2 if i + 1 < len(keys) \
            else min(k + spread, 127)
        rrs = by_key[k]
        for pos, f in enumerate(rrs, 1):
            rr = (' seq_length=%d seq_position=%d' % (len(rrs), pos)
                  if len(rrs) > 1 else '')
            lines.append('<region> sample=%s lokey=%d hikey=%d '
                         'pitch_keycenter=%d%s' % (f, lo, hi, k, rr))
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, 'w', encoding='utf-8') as fh:
        fh.write('\n'.join(lines) + '\n')
    return True


# (source folder under the shelf, octave shift, output name, spread)
MAPS = [
    ('VSCO2-CE/Brass/OldTrombone/Fall', 0, 'trombone-falls.sfz', 24),
    ('VCSL/Aerophones/Reed Aerophones/Tenor Saxophone/Vibrato', 12,
     'tenor-sax.sfz', 3),
    ('VCSL/Aerophones/Reed Aerophones/Tenor Saxophone/Staccato', 12,
     'tenor-sax-stac.sfz', 3),
    ('VCSL/Aerophones/Reed Aerophones/Saxello/Vibrato', 12,
     'saxello.sfz', 3),
    ('VCSL/Aerophones/Reed Aerophones/Saxello/Staccato', 12,
     'saxello-stac.sfz', 3),
]


# ------------------------------------------------------------- choir
#
# VocalSet (CC-BY 4.0, 20 professional singers) ships long tones per
# singer, vowel and dynamic — pp, straight, forte are three real
# velocity layers. Nobody labels the pitch, so we measure it: Goertzel
# over the semitone grid, fundamental preferred over its harmonic,
# then a cent-level refinement written as the region's tune. Singers
# landing on the same note stack — that IS the choir.

_VOWEL_MAPS = {'a': 'choir-ah.sfz', 'o': 'choir-oh.sfz',
               'u': 'choir-oo.sfz'}
_DYN_LAYERS = {'pp': (1, 45), 'straight': (46, 95), 'forte': (96, 127)}


def _detect_pitch(path):
    """(midi, cents_off, rms_db) of a sustained tone, or None. The
    level rides along because VocalSet's singers sit at very different
    distances — a choir needs its voices brought to one loudness."""
    import math
    try:
        import sfz as _sfz
        got = _sfz._read_wav(path)
    except Exception:
        return None
    if got is None:
        return None
    L, _R, sr, _loop = got
    n = len(L)
    if n < sr:
        return None
    seg = L[n // 3:n // 3 + 8192]
    rms = math.sqrt(sum(v * v for v in seg) / len(seg)) or 1e-6
    rms_db = 20 * math.log10(rms / 30000.0)
    # the breath before the tone: skip to the first real signal, a
    # touch early so the attack keeps its consonant of air
    peak = max(abs(v) for v in L) or 1.0
    onset = 0
    for i in range(n):
        if abs(L[i]) > 0.04 * peak:
            onset = max(i - int(0.02 * sr), 0)
            break

    def g(freq):
        w = 2 * math.pi * freq / sr
        c = 2 * math.cos(w)
        s0 = s1 = 0.0
        for v in seg:
            s0, s1 = v + c * s0 - s1, s0
        return math.sqrt(abs(s1 * s1 + s0 * s0 - c * s0 * s1))

    scores = {}
    for midi in range(36, 85):
        f = 440.0 * 2 ** ((midi - 69) / 12.0)
        scores[midi] = g(f) + 0.5 * g(2 * f)
    top = max(scores.values())
    if top <= 0:
        return None
    best = min(m for m, s in scores.items() if s >= 0.5 * top)
    f0 = 440.0 * 2 ** ((best - 69) / 12.0)
    ref = -1
    cents = 0
    for c in range(-50, 51, 10):
        s = g(f0 * 2 ** (c / 1200.0))
        if s > ref:
            ref, cents = s, c
    return best, cents, rms_db, onset


def build_choir(shelf):
    """VocalSet long tones -> choir-ah/oh/oo.sfz with three velocity
    layers, singers stacked per note. Pitch analysis caches to JSON so
    a rebuild costs nothing."""
    import json
    root = os.path.join(shelf, 'VocalSet', 'FULL')
    if not os.path.isdir(root):
        return []
    cache_path = os.path.join(shelf, 'Copyist-Extras',
                              'vocalset-pitches.json')
    try:
        cache = json.load(open(cache_path, encoding='utf-8'))
    except Exception:
        cache = {}
    tones = {}                  # (vowel, dyn) -> [(midi, cents, rel)]
    for singer in sorted(os.listdir(root)):
        for dyn in _DYN_LAYERS:
            folder = os.path.join(root, singer, 'long_tones', dyn)
            if not os.path.isdir(folder):
                continue
            for f in sorted(os.listdir(folder)):
                if not f.lower().endswith('.wav'):
                    continue
                vowel = os.path.splitext(f)[0].rsplit('_', 1)[-1]
                if vowel not in _VOWEL_MAPS:
                    continue
                rel = '/'.join((singer, 'long_tones', dyn, f))
                got = cache.get(rel)
                if not got or len(got) < 4:
                    got = _detect_pitch(os.path.join(folder, f))
                    cache[rel] = got
                if got:
                    tones.setdefault((vowel, dyn), []).append(
                        (got[0], got[1], got[2], got[3], rel))
    os.makedirs(os.path.dirname(cache_path), exist_ok=True)
    json.dump(cache, open(cache_path, 'w', encoding='utf-8'))
    made = []
    for vowel, out_name in _VOWEL_MAPS.items():
        lines = ['// Generated by Copyist mkshelf from VocalSet '
                 '(CC-BY 4.0, credit in NOTICES) — edits do not last.',
                 '<control>', 'default_path=../VocalSet/FULL/', '']
        wrote = False
        for dyn, (lovel, hivel) in _DYN_LAYERS.items():
            notes = sorted(tones.get((vowel, dyn), ()))
            keys = sorted({m for m, _c, _d, _o, _r in notes})
            for i, k in enumerate(keys):
                lo = (keys[i - 1] + k) // 2 + 1 if i else max(k - 5, 0)
                hi = (k + keys[i + 1]) // 2 if i + 1 < len(keys) \
                    else min(k + 5, 127)
                stack = [n for n in notes if n[0] == k]
                for m, cents, rms_db, onset, rel in stack:
                    # every voice to one loudness (-24 dB RMS on the
                    # engine scale), minus a share for stacking
                    vol = -24.0 - rms_db - 3.0 * (len(stack) - 1)
                    vol = min(max(vol, -30.0), 18.0)
                    lines.append(
                        '<region> sample=%s lokey=%d hikey=%d '
                        'pitch_keycenter=%d tune=%d lovel=%d hivel=%d '
                        'volume=%.1f offset=%d ampeg_release=0.2'
                        % (rel, lo, hi, k, -cents, lovel, hivel, vol,
                           onset))
                    wrote = True
        if wrote:
            out = os.path.join(shelf, 'Copyist-Extras', out_name)
            with open(out, 'w', encoding='utf-8') as fh:
                fh.write('\n'.join(lines) + '\n')
            made.append(out_name)
    return made


# ------------------------------------------------------------- organ
#
# No openly licensed deep multisample of a real tonewheel organ
# exists (verified hard, 2026-09-21). But a tonewheel organ is the
# one instrument additive synthesis genuinely IS: 91 sine wheels,
# drawbars mixing nine harmonics with foldback at the top, percussion
# borrowing the third harmonic for a beat, key click, and a Leslie —
# amplitude, vibrato and stereo movement from a spinning horn over a
# slower drum. So Copyist renders its own B3 sample set, offline,
# and owns every byte. Two registrations, both Leslie speeds.

_ORGANS = [
    # (name, drawbars 16' 5 1/3' 8' 4' 2 2/3' 2' 1 3/5' 1 1/3' 1',
    #  percussion, leslie_hz)
    ('organ-gospel-fast', (8, 8, 8, 8, 6, 6, 5, 5, 4), True, 6.8),
    ('organ-gospel-slow', (8, 8, 8, 8, 6, 6, 5, 5, 4), True, 0.72),
    ('organ-jazz-slow', (8, 8, 8, 0, 0, 0, 0, 0, 0), True, 0.72),
]
_HARM = (0.5, 1.5, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 8.0)


def _render_organ_note(freq, drawbars, percussion, leslie_hz, sr,
                       seconds=8.0):
    """One tonewheel note through the Leslie -> (L, R) float lists."""
    import math
    n = int(seconds * sr)
    L = [0.0] * n
    R = [0.0] * n
    two_pi = 2 * math.pi
    for bar, mult in zip(drawbars, _HARM):
        if not bar:
            continue
        f = freq * mult
        while f > 5924.6:               # tonewheel foldback, the real
            f /= 2.0                    # generator's top octave
        amp = (bar / 8.0) ** 1.5 * 3000.0
        # the horn spins: vibrato plus tremolo, upper partials moving
        # harder than the drum-fed lows (crossover near 800 Hz)
        horn = min(max((f - 400.0) / 800.0, 0.15), 1.0)
        fm = 0.006 * horn               # ~10 cents at full horn
        am = 0.35 * horn
        rate = two_pi * leslie_hz / sr
        w = two_pi * f / sr
        phase = 0.0
        rot = 0.0
        for i in range(n):
            rot = rate * i
            m = math.sin(rot)
            phase += w * (1.0 + fm * m)
            s = math.sin(phase) * amp
            # two virtual mics, the horn sweeping between them
            L[i] += s * (1.0 + am * m)
            R[i] += s * (1.0 - am * m)
    if percussion:
        f = freq * 3.0
        while f > 5924.6:
            f /= 2.0
        w = two_pi * f / sr
        dec = math.exp(math.log(0.001) / (0.35 * sr))
        env = 1.0
        for i in range(int(0.35 * sr)):
            s = math.sin(w * i) * env * 2600.0
            env *= dec
            L[i] += s
            R[i] += s
    # key click: a few ms of filtered noise at the attack
    x = 1234567
    for i in range(int(0.004 * sr)):
        x = (x * 1103515245 + 12345) & 0x7FFFFFFF
        s = ((x / 0x3FFFFFFF) - 1.0) * 900.0 * (1.0 - i / (0.004 * sr))
        L[i] += s
        R[i] += s
    return L, R


def build_organ(shelf, sr=44100):
    """Render the tonewheel set (every third semitone, C1..C6) and
    write one SFZ per registration. Skips work already on disk."""
    import struct as _st
    import wave as _wave
    out_dir = os.path.join(shelf, 'Copyist-Extras', 'organ-samples')
    os.makedirs(out_dir, exist_ok=True)
    made = []
    keys = list(range(24, 85, 3))
    for name, bars, perc, hz in _ORGANS:
        lines = ['// Rendered by Copyist mkshelf — its own tonewheels',
                 '// and Leslie; CC0 by construction. Edits do not',
                 '// last.', '<control>', 'default_path=organ-samples/',
                 '', '<group>', 'ampeg_release=0.25', 'loop_mode=loop_continuous',
                 'loop_start=%d' % (2 * sr), 'loop_end=%d' % (6 * sr - 1), '']
        for i, k in enumerate(keys):
            wav_name = '%s_%d.wav' % (name, k)
            p = os.path.join(out_dir, wav_name)
            if not os.path.exists(p):
                freq = 440.0 * 2 ** ((k - 69) / 12.0)
                L, R = _render_organ_note(freq, bars, perc, hz, sr)
                frames = bytearray()
                for a, b in zip(L, R):
                    frames += _st.pack('<hh',
                                       int(max(-1, min(1, a / 32767.0))
                                           * 32767),
                                       int(max(-1, min(1, b / 32767.0))
                                           * 32767))
                with _wave.open(p, 'wb') as w:
                    w.setnchannels(2)
                    w.setsampwidth(2)
                    w.setframerate(sr)
                    w.writeframes(bytes(frames))
            lo = keys[i - 1] + 2 if i else 0
            hi = k + 1 if i + 1 < len(keys) else 127
            lines.append('<region> sample=%s lokey=%d hikey=%d '
                         'pitch_keycenter=%d' % (wav_name, lo, hi, k))
        sfz_path = os.path.join(shelf, 'Copyist-Extras',
                                name + '.sfz')
        with open(sfz_path, 'w', encoding='utf-8') as fh:
            fh.write('\n'.join(lines) + '\n')
        made.append(name + '.sfz')
    return made


def main(shelf):
    made = []
    for rel, shift, name, spread in MAPS:
        src = os.path.join(shelf, rel)
        if not os.path.isdir(src):
            continue
        out = os.path.join(shelf, 'Copyist-Extras', name)
        if write_map(out, os.path.join('..', rel), scan(src, shift),
                     spread):
            made.append(name)
    made.extend(build_choir(shelf))
    return made


if __name__ == '__main__':
    shelf = sys.argv[1] if len(sys.argv) > 1 else os.path.expanduser(
        '~/Library/Application Support/Copyist/Sounds')
    for name in main(shelf):
        print('wrote', name)
